model:
  lstm_dim: 512
  conv_dim: 512
training:
  optimizer:
    learning_rate: 1e-4
    eps: 1e-8
    weight_decay: 0.01
    betas: [0.9, 0.98]
  binned_sampler: True
  plot_steps: 1000
  extraction_method: "dijkstra"
  batch_size: 32
  train_split: 0.99
  save_top_k_ckpts: 3
  ckpt_steps: null
  ckpt_epochs: 1
  max_epochs: 1000
  seed: 1234
  finetune_checkpoint: null
  filelist: "./preprocessed/YourDataSet/processed_filelist.psv"
  filelist_loader: "smts.utils.generic_dict_loader"
  logger:
    name: "Base Experiment"
    save_dir: "./logs"
    sub_dir: "smts.utils.get_current_time"
    version: "alignment-base"
  val_data_workers: 0
  train_data_workers: 0
preprocessing: "./config/default/preprocessing.yaml"
text: "./config/default/text_eng.yaml"
